# Generated by Django 4.2.7 on 2023-12-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_organization_language'),
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='level.level')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Level Organization',
                'verbose_name_plural': 'Level Organizations',
                'db_table': 'level_organization',
            },
        ),
        migrations.DeleteModel(
            name='LevelCredantials',
        ),
    ]
