# Generated by Django 4.2.7 on 2023-12-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_levelorganization_delete_levelcredantials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Level',
            new_name='LevelType',
        ),
        migrations.AlterModelOptions(
            name='leveltype',
            options={'verbose_name': 'Level Type', 'verbose_name_plural': 'Level Types'},
        ),
        migrations.AddIndex(
            model_name='levelorganization',
            index=models.Index(fields=['level', 'organization'], name='level_organ_level_i_057c47_idx'),
        ),
        migrations.AlterModelTable(
            name='leveltype',
            table='level_type',
        ),
    ]
