# Generated by Django 4.2.7 on 2023-12-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_rename_level_leveltype_alter_leveltype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveltype',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
