# Generated by Django 4.2.7 on 2023-12-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_leveltype_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveltype',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Красный (red)'), ('#FFA500', 'Оранжевый (orange)'), ('#FFFF00', 'Желтый (yellow)'), ('#008000', 'Зеленый (green)'), ('#0000FF', 'Синий (blue)'), ('#4B0082', 'Фиолетовый (purple)'), ('#800080', 'Фиолетовый (purple)'), ('#FFC0CB', 'Розовый (pink)'), ('#000000', 'Черный (black)'), ('#FFFFFF', 'Белый (white)')], default='#FF0000', max_length=255),
        ),
    ]
