# Generated by Django 4.2.7 on 2023-12-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('television', '0002_files_content_en_files_content_oz_files_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='televisiontype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='televisiontype',
            name='name_oz',
        ),
        migrations.RemoveField(
            model_name='televisiontype',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='televisiontype',
            name='name_uz',
        ),
        migrations.AddField(
            model_name='televisiontype',
            name='attr',
            field=models.CharField(default=2, max_length=255, verbose_name='Attribute'),
            preserve_default=False,
        ),
    ]
