# Generated by Django 4.2.7 on 2023-12-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('television', '0004_files_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestatus',
            name='attr',
            field=models.CharField(default=2, max_length=35, verbose_name='Attribute'),
            preserve_default=False,
        ),
    ]
