# Generated by Django 4.2.7 on 2023-12-01 12:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'Userth this phone number already exists.'}, help_text='Required. Only international format used. (998901234567)', max_length=128, null=True, region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
