# Generated by Django 4.2.7 on 2023-12-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_organization_language'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('reactions', models.PositiveIntegerField(default=0)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('social', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.social')),
            ],
            options={
                'verbose_name': 'Social Stat',
                'verbose_name_plural': 'Social Stats',
                'db_table': 'social_stats',
                'indexes': [models.Index(fields=['social'], name='social_stat_social__c9fcf7_idx'), models.Index(fields=['created_at'], name='social_stat_created_cd9c5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(blank=True, null=True)),
                ('post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('media_group_id', models.CharField(blank=True, max_length=24, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization')),
                ('social', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.social')),
            ],
            options={
                'verbose_name': 'Social Post',
                'verbose_name_plural': 'Social Posts',
                'db_table': 'social_posts',
                'indexes': [models.Index(fields=['post_date'], name='social_post_post_da_551584_idx'), models.Index(fields=['social'], name='social_post_social__ab1d72_idx'), models.Index(fields=['organization'], name='social_post_organiz_9f56e4_idx')],
            },
        ),
    ]
