# Generated by Django 4.2.7 on 2023-12-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_remove_category_status_remove_district_status_and_more'),
        ('social', '0002_socialstats_socialpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state'),
        ),
        migrations.AddField(
            model_name='socialtypes',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state'),
        ),
    ]
