# Generated by Django 4.2.7 on 2023-12-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_social_state_socialtypes_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='integration_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='tg_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
