# Generated by Django 4.2.7 on 2023-12-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_remove_category_status_remove_district_status_and_more'),
        ('social', '0004_social_integration_id_social_tg_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['state'], name='social_post_state_i_7e6ba9_idx'),
        ),
    ]
