# Generated by Django 4.2.7 on 2023-12-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_rename_socialstats_socialpoststats'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpoststats',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.socialpost'),
        ),
    ]
