# Generated by Django 4.2.7 on 2023-12-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_socialpoststats_post'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='socialpoststats',
            index=models.Index(fields=['post'], name='social_stat_post_id_052e2b_idx'),
        ),
    ]
