# Generated by Django 4.2.7 on 2023-12-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_organization_language'),
        ('social', '0009_remove_socialpost_social_post_social__ab1d72_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_to_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('media_group_id', models.CharField(blank=True, max_length=24, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization')),
                ('social_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.socialtypes')),
            ],
            options={
                'verbose_name': 'Social Post Comment',
                'verbose_name_plural': 'Social Post Comments',
                'db_table': 'social_post_comments',
                'indexes': [models.Index(fields=['social_type'], name='social_post_social__71171e_idx'), models.Index(fields=['organization'], name='social_post_organiz_4b7212_idx')],
            },
        ),
    ]
