# Generated by Django 4.2.7 on 2023-12-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_socialpostcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpostcomment',
            name='reply_to_message_id',
        ),
    ]
