# Generated by Django 4.2.7 on 2023-12-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_socialpostcomment_post'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='socialpostcomment',
            index=models.Index(fields=['post'], name='social_post_post_id_d46cc8_idx'),
        ),
    ]
