# Generated by Django 4.2.7 on 2023-12-04 14:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300, null=True, verbose_name='fullname')),
                ('fullname_oz', models.CharField(max_length=300, null=True, verbose_name='fullname')),
                ('fullname_uz', models.CharField(max_length=300, null=True, verbose_name='fullname')),
                ('fullname_en', models.CharField(max_length=300, null=True, verbose_name='fullname')),
                ('fullname_ru', models.CharField(max_length=300, null=True, verbose_name='fullname')),
                ('shortname', models.CharField(max_length=100, null=True, verbose_name='shortname')),
                ('shortname_oz', models.CharField(max_length=100, null=True, verbose_name='shortname')),
                ('shortname_uz', models.CharField(max_length=100, null=True, verbose_name='shortname')),
                ('shortname_en', models.CharField(max_length=100, null=True, verbose_name='shortname')),
                ('shortname_ru', models.CharField(max_length=100, null=True, verbose_name='shortname')),
                ('address', models.TextField(null=True, verbose_name='Address input')),
                ('address_oz', models.TextField(null=True, verbose_name='Address input')),
                ('address_uz', models.TextField(null=True, verbose_name='Address input')),
                ('address_en', models.TextField(null=True, verbose_name='Address input')),
                ('address_ru', models.TextField(null=True, verbose_name='Address input')),
                ('inn', models.CharField(max_length=9, null=True, verbose_name='INN')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'User with this phone number already exists.'}, help_text='Required. Only international format used.', max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('accounter', models.CharField(max_length=250, null=True, verbose_name='accounter')),
                ('leader', models.CharField(max_length=250, null=True, verbose_name='leader')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.category')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.district')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.region')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.specialization')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization',
                'indexes': [models.Index(fields=['shortname'], name='organizatio_shortna_1e90cf_idx'), models.Index(fields=['category'], name='organizatio_categor_66cd26_idx'), models.Index(fields=['specialization'], name='organizatio_special_fc45a9_idx'), models.Index(fields=['region'], name='organizatio_region__ab4442_idx'), models.Index(fields=['district'], name='organizatio_distric_6e9b70_idx'), models.Index(fields=['phone_number'], name='organizatio_phone_n_db1dca_idx')],
            },
        ),
    ]
