# Generated by Django 4.2.7 on 2023-12-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['shortname'], name='organizatio_shortna_1e90cf_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['category'], name='organizatio_categor_66cd26_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['specialization'], name='organizatio_special_fc45a9_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['region'], name='organizatio_region__ab4442_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['district'], name='organizatio_distric_6e9b70_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['phone_number'], name='organizatio_phone_n_db1dca_idx'),
        ),
    ]
