# Generated by Django 4.2.7 on 2023-12-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='language',
        ),
    ]
