# Generated by Django 4.2.7 on 2023-12-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fullname_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='fullname_oz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='fullname_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='fullname_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='shortname_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='shortname_oz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='shortname_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='shortname_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='fullname_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='fullname_oz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='fullname_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='fullname_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='shortname_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='shortname_oz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='shortname_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='shortname_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fullname_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fullname_oz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fullname_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='fullname_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='shortname_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='shortname_oz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='shortname_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='shortname_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='fullname_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='fullname_oz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='fullname_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='fullname_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='shortname_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='shortname_oz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='shortname_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='shortname_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name_oz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
