# Generated by Django 4.2.7 on 2023-12-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_category_fullname_en_category_fullname_oz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='district',
            name='status',
        ),
        migrations.RemoveField(
            model_name='region',
            name='status',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='status',
        ),
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='utils.state'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='utils.state'),
        ),
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='utils.state'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialization', to='utils.state'),
        ),
    ]
