# Generated by Django 4.2.7 on 2023-12-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_remove_category_status_remove_district_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('file_name_oz', models.CharField(max_length=250, null=True)),
                ('file_name_uz', models.CharField(max_length=250, null=True)),
                ('file_name_en', models.CharField(max_length=250, null=True)),
                ('file_name_ru', models.CharField(max_length=250, null=True)),
                ('file_id', models.CharField(blank=True, max_length=250, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_oz', models.TextField(blank=True, null=True)),
                ('content_uz', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('content_ru', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruction', to='utils.state')),
            ],
            options={
                'verbose_name': 'Instruction',
                'verbose_name_plural': 'Instructions',
                'db_table': 'instruction',
            },
        ),
    ]
